export const sidebarLinks = [
  {
    imgURL: "/icons/home.svg",
    route: "/",
    label: "Home",
  },
  {
    imgURL: "/icons/users.svg",
    route: "/community",
    label: "Community",
  },
  {
    imgURL: "/icons/star.svg",
    route: "/collections",
    label: "Collections",
  },
  {
    imgURL: "/icons/suitcase.svg",
    route: "/jobs",
    label: "Find Jobs",
  },
  {
    imgURL: "/icons/tag.svg",
    route: "/tags",
    label: "Tags",
  },
  {
    imgURL: "/icons/user.svg",
    route: "/profile",
    label: "Profile",
  },
  {
    imgURL: "/icons/question.svg",
    route: "/ask-question",
    label: "Ask a question",
  },
];

export  const techMap: { [key: string]: string } = {
    javascript: "devicon-javascript-plain",
    typescript: "devicon-typescript-plain",
    python: "devicon-python-plain",
    java: "devicon-java-plain",
    csharp: "devicon-csharp-plain",
    php: "devicon-php-plain",
    ruby: "devicon-ruby-plain",
    go: "devicon-go-plain",
    rust: "devicon-rust-plain",
    kotlin: "devicon-kotlin-plain",
    swift: "devicon-swift-plain",
    html5: "devicon-html5-plain",
    css3: "devicon-css3-plain",
    react: "devicon-react-plain",
    angular: "devicon-angularjs-plain",
    vuejs: "devicon-vuejs-plain",
    nextjs: "devicon-nextjs-plain",
    tailwindcss: "devicon-tailwindcss-plain",
    nodejs: "devicon-nodejs-plain",
    django: "devicon-django-plain",
    flask: "devicon-flask-plain",
    spring: "devicon-spring-plain",
    laravel: "devicon-laravel-plain",
    mysql: "devicon-mysql-plain",
    postgresql: "devicon-postgresql-plain",
    mongodb: "devicon-mongodb-plain",
    docker: "devicon-docker-plain",
    kubernetes: "devicon-kubernetes-plain",
    c: "devicon-c-plain",
    cpp: "devicon-cplusplus-plain",
    r: "devicon-r-plain",
    scala: "devicon-scala-plain",
    haskell: "devicon-haskell-plain",
    lua: "devicon-lua-plain",
    perl: "devicon-perl-plain",
    dart: "devicon-dart-plain",
    elixir: "devicon-elixir-plain",
    clojure: "devicon-clojure-plain",
    erlang: "devicon-erlang-plain",
    julia: "devicon-julia-plain",
    matlab: "devicon-matlab-plain",
    fortran: "devicon-fortran-plain",
    cobol: "devicon-cobol-plain",
    assembly: "devicon-assembly-plain",
    verilog: "devicon-verilog-plain",
    vhdl: "devicon-vhdl-plain",
    svelte: "devicon-svelte-plain",
    solidjs: "devicon-solidjs-plain",
    qwik: "devicon-qwik-plain",
    astro: "devicon-astro-plain",
    remix: "devicon-remix-plain",
    gatsby: "devicon-gatsby-plain",
    express: "devicon-express-plain",
    fastify: "devicon-fastify-plain",
    nestjs: "devicon-nestjs-plain",
    rails: "devicon-rails-plain",
    phoenix: "devicon-phoenix-plain",
    dotnet: "devicon-dot-net-plain",
    blazor: "devicon-blazor-plain",
    flutter: "devicon-flutter-plain",
    reactnative: "devicon-reactnative-plain",
    ionic: "devicon-ionic-plain",
    capacitor: "devicon-capacitor-plain",
    electron: "devicon-electron-plain",
    tauri: "devicon-tauri-plain",
    redis: "devicon-redis-plain",
    sqlite: "devicon-sqlite-plain",
    cassandra: "devicon-cassandra-plain",
    couchdb: "devicon-couchdb-plain",
    dynamodb: "devicon-dynamodb-plain",
    firebase: "devicon-firebase-plain",
    supabase: "devicon-supabase-plain",
    prisma: "devicon-prisma-plain",
    sequelize: "devicon-sequelize-plain",
    mongoose: "devicon-mongoose-plain",
    oracle: "devicon-oracle-plain",
    mariadb: "devicon-mariadb-plain",
    clickhouse: "devicon-clickhouse-plain",
    git: "devicon-git-plain",
    github: "devicon-github-plain",
    gitlab: "devicon-gitlab-plain",
    jenkins: "devicon-jenkins-plain",
    travis: "devicon-travis-plain",
    circleci: "devicon-circleci-plain",
    githubactions: "devicon-githubactions-plain",
    terraform: "devicon-terraform-plain",
    ansible: "devicon-ansible-plain",
    vagrant: "devicon-vagrant-plain",
    aws: "devicon-amazonwebservices-plain",
    azure: "devicon-azure-plain",
    gcp: "devicon-googlecloud-plain",
    heroku: "devicon-heroku-plain",
    netlify: "devicon-netlify-plain",
    vercel: "devicon-vercel-plain",
    nginx: "devicon-nginx-plain",
    apache: "devicon-apache-plain",
    tomcat: "devicon-tomcat-plain",
    linux: "devicon-linux-plain",
    ubuntu: "devicon-ubuntu-plain",
    centos: "devicon-centos-plain",
    fedora: "devicon-fedora-plain",
    debian: "devicon-debian-plain",
    archlinux: "devicon-archlinux-plain",
    windows: "devicon-windows11-plain",
    macos: "devicon-apple-plain",
    ios: "devicon-ios-plain",
    android: "devicon-android-plain",
    vscode: "devicon-vscode-plain",
    vim: "devicon-vim-plain",
    emacs: "devicon-emacs-plain",
    sublimetext: "devicon-sublimetext-plain",
    atom: "devicon-atom-plain",
    intellij: "devicon-intellij-plain",
    webstorm: "devicon-webstorm-plain",
    pycharm: "devicon-pycharm-plain",
    sass: "devicon-sass-plain",
    less: "devicon-less-plain",
    stylus: "devicon-stylus-plain",
    bootstrap: "devicon-bootstrap-plain",
    bulma: "devicon-bulma-plain",
    materialui: "devicon-materialui-plain",
    jquery: "devicon-jquery-plain",
    redux: "devicon-redux-plain",
    rxjs: "devicon-rxjs-plain",
    d3js: "devicon-d3js-plain",
    chartjs: "devicon-chartjs-plain",
    numpy: "devicon-numpy-plain",
    pandas: "devicon-pandas-plain",
    matplotlib: "devicon-matplotlib-plain",
    scikitlearn: "devicon-scikitlearn-plain",
    tensorflow: "devicon-tensorflow-plain",
    pytorch: "devicon-pytorch-plain",
    opencv: "devicon-opencv-plain",
    maven: "devicon-maven-plain",
    gradle: "devicon-gradle-plain",
    junit: "devicon-junit-plain",
    composer: "devicon-composer-plain",
    phpunit: "devicon-phpunit-plain",
    rspec: "devicon-rspec-plain",
    css: "devicon-css3-plain",
    html: "devicon-html5-plain",
    appwrite: "devicon-appwrite-plain",
  };