/**
 * 5 minutes in milliseconds
 */
export const DEFAULT_CACHE_DURATION = 300;

export const sidebarLinks = [
  {
    imgURL: "/icons/home.svg",
    route: "/",
    label: "Home",
  },
  {
    imgURL: "/icons/users.svg",
    route: "/community",
    label: "Community",
  },
  {
    imgURL: "/icons/star.svg",
    route: "/collections",
    label: "Collections",
  },
  {
    imgURL: "/icons/suitcase.svg",
    route: "/jobs",
    label: "Find Jobs",
  },
  {
    imgURL: "/icons/tag.svg",
    route: "/tags",
    label: "Tags",
  },
  {
    imgURL: "/icons/user.svg",
    route: "/profile",
    label: "Profile",
  },
  {
    imgURL: "/icons/question.svg",
    route: "/ask-question",
    label: "Ask a question",
  },
];



export const techMap: { [key: string]: string } = {
  javascript: "devicon-javascript-plain",
  typescript: "devicon-typescript-plain",
  python: "devicon-python-plain",
  java: "devicon-java-plain",
  csharp: "devicon-csharp-plain",
  php: "devicon-php-plain",
  ruby: "devicon-ruby-plain",
  go: "devicon-go-plain",
  rust: "devicon-rust-plain",
  kotlin: "devicon-kotlin-plain",
  swift: "devicon-swift-plain",
  html5: "devicon-html5-plain",
  css3: "devicon-css3-plain",
  react: "devicon-react-plain",
  angular: "devicon-angularjs-plain",
  vuejs: "devicon-vuejs-plain",
  nextjs: "devicon-nextjs-plain",
  tailwindcss: "devicon-tailwindcss-plain",
  nodejs: "devicon-nodejs-plain",
  django: "devicon-django-plain",
  flask: "devicon-flask-plain",
  spring: "devicon-spring-plain",
  laravel: "devicon-laravel-plain",
  mysql: "devicon-mysql-plain",
  postgresql: "devicon-postgresql-plain",
  mongodb: "devicon-mongodb-plain",
  docker: "devicon-docker-plain",
  kubernetes: "devicon-kubernetes-plain",
  c: "devicon-c-plain",
  cpp: "devicon-cplusplus-plain",
  r: "devicon-r-plain",
  scala: "devicon-scala-plain",
  haskell: "devicon-haskell-plain",
  lua: "devicon-lua-plain",
  perl: "devicon-perl-plain",
  dart: "devicon-dart-plain",
  elixir: "devicon-elixir-plain",
  clojure: "devicon-clojure-plain",
  erlang: "devicon-erlang-plain",
  julia: "devicon-julia-plain",
  matlab: "devicon-matlab-plain",
  fortran: "devicon-fortran-plain",
  cobol: "devicon-cobol-plain",
  assembly: "devicon-assembly-plain",
  verilog: "devicon-verilog-plain",
  vhdl: "devicon-vhdl-plain",
  svelte: "devicon-svelte-plain",
  solidjs: "devicon-solidjs-plain",
  qwik: "devicon-qwik-plain",
  astro: "devicon-astro-plain",
  remix: "devicon-remix-plain",
  gatsby: "devicon-gatsby-plain",
  express: "devicon-express-plain",
  fastify: "devicon-fastify-plain",
  nestjs: "devicon-nestjs-plain",
  rails: "devicon-rails-plain",
  phoenix: "devicon-phoenix-plain",
  dotnet: "devicon-dot-net-plain",
  blazor: "devicon-blazor-plain",
  flutter: "devicon-flutter-plain",
  reactnative: "devicon-reactnative-plain",
  ionic: "devicon-ionic-plain",
  capacitor: "devicon-capacitor-plain",
  electron: "devicon-electron-plain",
  tauri: "devicon-tauri-plain",
  redis: "devicon-redis-plain",
  sqlite: "devicon-sqlite-plain",
  cassandra: "devicon-cassandra-plain",
  couchdb: "devicon-couchdb-plain",
  dynamodb: "devicon-dynamodb-plain",
  firebase: "devicon-firebase-plain",
  supabase: "devicon-supabase-plain",
  prisma: "devicon-prisma-plain",
  sequelize: "devicon-sequelize-plain",
  mongoose: "devicon-mongoose-plain",
  oracle: "devicon-oracle-plain",
  mariadb: "devicon-mariadb-plain",
  clickhouse: "devicon-clickhouse-plain",
  git: "devicon-git-plain",
  github: "devicon-github-plain",
  gitlab: "devicon-gitlab-plain",
  jenkins: "devicon-jenkins-plain",
  travis: "devicon-travis-plain",
  circleci: "devicon-circleci-plain",
  githubactions: "devicon-githubactions-plain",
  terraform: "devicon-terraform-plain",
  ansible: "devicon-ansible-plain",
  vagrant: "devicon-vagrant-plain",
  aws: "devicon-amazonwebservices-plain",
  azure: "devicon-azure-plain",
  gcp: "devicon-googlecloud-plain",
  heroku: "devicon-heroku-plain",
  netlify: "devicon-netlify-plain",
  vercel: "devicon-vercel-plain",
  nginx: "devicon-nginx-plain",
  apache: "devicon-apache-plain",
  tomcat: "devicon-tomcat-plain",
  linux: "devicon-linux-plain",
  ubuntu: "devicon-ubuntu-plain",
  centos: "devicon-centos-plain",
  fedora: "devicon-fedora-plain",
  debian: "devicon-debian-plain",
  archlinux: "devicon-archlinux-plain",
  windows: "devicon-windows11-plain",
  macos: "devicon-apple-plain",
  ios: "devicon-ios-plain",
  android: "devicon-android-plain",
  vscode: "devicon-vscode-plain",
  vim: "devicon-vim-plain",
  emacs: "devicon-emacs-plain",
  sublimetext: "devicon-sublimetext-plain",
  atom: "devicon-atom-plain",
  intellij: "devicon-intellij-plain",
  webstorm: "devicon-webstorm-plain",
  pycharm: "devicon-pycharm-plain",
  sass: "devicon-sass-plain",
  less: "devicon-less-plain",
  stylus: "devicon-stylus-plain",
  bootstrap: "devicon-bootstrap-plain",
  bulma: "devicon-bulma-plain",
  materialui: "devicon-materialui-plain",
  jquery: "devicon-jquery-plain",
  redux: "devicon-redux-plain",
  rxjs: "devicon-rxjs-plain",
  d3js: "devicon-d3js-plain",
  chartjs: "devicon-chartjs-plain",
  numpy: "devicon-numpy-plain",
  pandas: "devicon-pandas-plain",
  matplotlib: "devicon-matplotlib-plain",
  scikitlearn: "devicon-scikitlearn-plain",
  tensorflow: "devicon-tensorflow-plain",
  pytorch: "devicon-pytorch-plain",
  opencv: "devicon-opencv-plain",
  maven: "devicon-maven-plain",
  gradle: "devicon-gradle-plain",
  junit: "devicon-junit-plain",
  composer: "devicon-composer-plain",
  phpunit: "devicon-phpunit-plain",
  rspec: "devicon-rspec-plain",
  css: "devicon-css3-plain",
  html: "devicon-html5-plain",
  appwrite: "devicon-appwrite-plain",
};

export const techDescription: { [key: string]: string } = {
  javascript: "A dynamic, high-level language used for client- and server-side web development (ECMAScript standard).",
  typescript: "A statically-typed superset of JavaScript that adds optional types and compile-time checking.",
  python: "A versatile, readable programming language commonly used for web development, scripting, and data science.",
  java: "A class-based, object-oriented language used for enterprise systems, Android apps, and cross-platform applications.",
  csharp: "A modern, object-oriented language developed by Microsoft for .NET applications and game development with Unity.",
  php: "A server-side scripting language widely used for building dynamic web applications.",
  ruby: "A dynamic, expressive language known for its clean syntax and the Rails web framework.",
  go: "A statically-typed, compiled language by Google designed for simplicity and concurrency in networked services.",
  rust: "A performance-focused systems language that emphasizes memory safety and zero-cost abstractions.",
  kotlin: "A concise, modern language interoperable with Java and popular for Android development.",
  swift: "Apple's modern language for iOS, macOS, watchOS, and tvOS development, designed for safety and performance.",
  html5: "The standard markup language for structuring and presenting content on the web.",
  css3: "The style sheet language used to describe the look and layout of web pages, including responsive and visual features.",
  react: "A declarative JavaScript library for building component-based user interfaces.",
  angular: "A TypeScript-based front-end framework for building large-scale single-page applications.",
  vuejs: "A progressive JavaScript framework for building approachable and modular user interfaces.",
  nextjs: "A React framework providing server-side rendering, static generation, and full-stack features.",
  tailwindcss: "A utility-first CSS framework that enables rapid design using composable utility classes.",
  nodejs: "A JavaScript runtime built on Chrome's V8 engine for building scalable server-side applications.",
  django: "A high-level Python web framework that emphasizes rapid development and pragmatic design.",
  flask: "A lightweight Python web framework that is simple and highly extensible.",
  spring: "A comprehensive Java framework for building enterprise-grade applications with dependency injection.",
  laravel: "A PHP framework focused on elegant syntax, expressive tooling, and developer productivity.",
  mysql: "A widely-used open-source relational database management system.",
  postgresql: "A powerful, open-source relational database known for standards compliance and extensibility.",
  mongodb: "A NoSQL document database that stores data in flexible, JSON-like documents.",
  docker: "A platform for packaging, distributing, and running applications in lightweight containers.",
  kubernetes: "An orchestration system for automating deployment, scaling, and management of containerized apps.",
  c: "A foundational systems programming language known for performance and portability.",
  cpp: "An extension of C that adds object-oriented and generic programming features.",
  r: "A language and environment focused on statistics, data analysis, and visualization.",
  scala: "A JVM language that combines object-oriented and functional programming paradigms.",
  haskell: "A purely functional programming language with a strong type system and lazy evaluation.",
  lua: "A lightweight, embeddable scripting language often used for configuration and games.",
  perl: "A high-level scripting language known for text processing and system administration tasks.",
  dart: "A language optimized for building UI, primarily used with the Flutter framework.",
  elixir: "A functional, concurrent language on the Erlang VM designed for scalable, fault-tolerant systems.",
  clojure: "A modern, dynamic Lisp that runs on the JVM and emphasizes immutability and functional programming.",
  erlang: "A concurrent, fault-tolerant language originally designed for telecom systems and distributed systems.",
  julia: "A high-performance language for numerical and scientific computing with easy syntax.",
  matlab: "A numerical computing environment and language commonly used in engineering and research.",
  fortran: "A high-performance language traditionally used in scientific and numerical computing.",
  cobol: "A legacy business-oriented language still used in many enterprise mainframe systems.",
  assembly: "Low-level programming closely tied to CPU architecture, used for performance-critical and embedded code.",
  verilog: "A hardware description language used to model digital circuits and systems.",
  vhdl: "A hardware description language for designing and documenting digital and mixed-signal systems.",
  svelte: "A front-end framework that compiles components to minimal, highly-performant vanilla JavaScript.",
  solidjs: "A reactive UI library that uses fine-grained reactivity for high performance in web apps.",
  qwik: "A resumable web framework designed for instant-loading web apps with minimal runtime JavaScript.",
  astro: "A static-site builder that focuses on delivering minimal client-side JavaScript and fast pages.",
  remix: "A full-stack React framework that prioritizes web standards, routing, and data loading.",
  gatsby: "A React-based static site generator optimized for performance and rich data sourcing.",
  express: "A minimal and flexible Node.js web framework providing routing and middleware.",
  fastify: "A fast, low-overhead Node.js web framework focused on performance and developer experience.",
  nestjs: "A progressive Node.js framework using TypeScript and a modular architecture inspired by Angular.",
  rails: "A Ruby web framework emphasizing convention over configuration and rapid development.",
  phoenix: "An Elixir web framework that offers high performance and real-time features.",
  dotnet: ".NET — a cross-platform framework for building applications using languages like C#.",
  blazor: "A .NET framework for building interactive web UIs using C# and WebAssembly or server rendering.",
  flutter: "A UI toolkit for building natively compiled, cross-platform mobile, web, and desktop apps from a single codebase.",
  reactnative: "A framework for building native mobile apps using React and JavaScript.",
  ionic: "A hybrid mobile framework that uses web technologies and native wrappers for cross-platform apps.",
  capacitor: "A cross-platform runtime that enables web apps to run natively on iOS, Android, and the web.",
  electron: "A framework for building cross-platform desktop apps using web technologies and Node.js.",
  tauri: "A toolkit for building smaller, faster desktop apps by combining Rust backends with web frontends.",
  redis: "An in-memory key-value store commonly used as a cache, message broker, and fast datastore.",
  sqlite: "A lightweight, serverless SQL database engine embedded in applications.",
  cassandra: "A distributed NoSQL database designed for high availability and horizontal scalability.",
  couchdb: "A document-oriented NoSQL database with a RESTful HTTP/JSON API and multi-master replication.",
  dynamodb: "AWS's managed NoSQL service for key-value and document workloads with low-latency access.",
  firebase: "A Google-backed platform offering realtime databases, auth, hosting, and serverless features.",
  supabase: "An open-source alternative to Firebase that provides Postgres, auth, and storage services.",
  prisma: "An ORM and query builder for TypeScript and Node.js that generates type-safe database clients.",
  sequelize: "A promise-based Node.js ORM for SQL databases providing model abstractions.",
  mongoose: "An ODM for MongoDB that adds schema modeling and validation for Node.js apps.",
  oracle: "A commercial enterprise relational database with advanced features and extensive tooling.",
  mariadb: "A community-developed fork of MySQL that provides additional storage engines and features.",
  clickhouse: "A columnar database optimized for fast analytical queries on large datasets.",
  git: "A distributed version control system for tracking changes and collaboration on code.",
  github: "A code hosting platform built on Git with collaboration features, issue tracking, and CI/CD integration.",
  gitlab: "A DevOps platform offering Git repo management, CI/CD, and project lifecycle tools.",
  jenkins: "An open-source automation server for building, testing, and deploying software via pipelines.",
  travis: "A cloud-based continuous integration service historically popular with open-source projects.",
  circleci: "A continuous integration and delivery platform to automate builds and deployments.",
  githubactions: "GitHub's automation platform for CI/CD workflows and repository automation.",
  terraform: "An infrastructure-as-code tool for provisioning and managing cloud resources declaratively.",
  ansible: "An agentless automation tool for configuration management, orchestration, and app deployment.",
  vagrant: "A tool for building and managing reproducible development environments with virtual machines.",
  aws: "Amazon Web Services — a comprehensive cloud platform with compute, storage, and managed services.",
  azure: "Microsoft Azure — a cloud computing platform for building, deploying, and managing applications and services.",
  gcp: "Google Cloud Platform — a suite of cloud services that run on Google's infrastructure.",
  heroku: "A platform-as-a-service (PaaS) that simplifies app deployment and scaling.",
  netlify: "A platform for deploying and hosting static sites and serverless functions with easy CI integration.",
  vercel: "A platform for front-end developers offering serverless functions, static hosting, and instant deployments.",
  nginx: "A high-performance web server and reverse proxy commonly used for load balancing and static hosting.",
  apache: "A widely-used HTTP server with a modular architecture and a long history in web hosting.",
  tomcat: "An open-source Java servlet container used to deploy Java web applications.",
  linux: "An open-source operating system kernel that underlies many server, desktop, and embedded systems.",
  ubuntu: "A popular Linux distribution known for ease of use, strong community support, and regular releases.",
  centos: "A community-supported enterprise Linux distribution historically used for servers (various downstreams now exist).",
  fedora: "A cutting-edge Linux distribution often used by developers and early adopters for new upstream features.",
  debian: "A stable and widely-used Linux distribution known for robustness and package management.",
  archlinux: "A rolling-release Linux distribution aimed at experienced users who prefer simplicity and customization.",
  windows: "Microsoft Windows — a widely used desktop and server operating system.",
  macos: "Apple's desktop operating system for Mac computers, known for a polished user experience.",
  ios: "Apple's mobile operating system for iPhone and iPad devices.",
  android: "Google's mobile operating system that powers a large portion of smartphones worldwide.",
  vscode: "Visual Studio Code — a powerful, extensible source-code editor popular for many languages.",
  vim: "A modal, keyboard-driven text editor valued for speed and efficiency in code editing.",
  emacs: "An extensible, customizable text editor and computing environment with a rich package ecosystem.",
  sublimetext: "A fast, lightweight text editor focused on performance and minimal UI.",
  atom: "A hackable text editor built with web technologies (now archived but historically influential).",
  intellij: "A JetBrains IDE family known for intelligent coding assistance, especially for JVM languages.",
  webstorm: "A JetBrains IDE tailored for JavaScript and TypeScript development workflows.",
  pycharm: "A JetBrains IDE specialized for Python development with smart tooling and debugging.",
  sass: "A CSS preprocessor that adds variables, nesting, and mixins to make stylesheets more maintainable.",
  less: "A CSS preprocessor offering variables and mixins to simplify stylesheet authoring.",
  stylus: "A flexible CSS preprocessor with concise syntax and powerful features.",
  bootstrap: "A popular front-end component library and CSS framework for building responsive sites quickly.",
  bulma: "A modern CSS framework based on Flexbox with straightforward, class-based syntax.",
  materialui: "A React component library implementing Google's Material Design for consistent UI.",
  jquery: "A JavaScript library that historically simplified DOM manipulation and AJAX interactions.",
  redux: "A predictable state container for JavaScript apps, often used with React.",
  rxjs: "A library for composing asynchronous and event-based programs using observables.",
  d3js: "A JavaScript library for creating dynamic, data-driven visualizations in the browser.",
  chartjs: "A lightweight JavaScript library for drawing common chart types with a simple API.",
  numpy: "A foundational Python library providing fast numerical arrays and math routines.",
  pandas: "A Python library for data manipulation and analysis using DataFrame abstractions.",
  matplotlib: "A Python plotting library for creating static, animated, and interactive visualizations.",
  scikitlearn: "A Python library providing tools for classical machine learning and model evaluation.",
  tensorflow: "An open-source platform for machine learning and deep learning developed by Google.",
  pytorch: "A flexible machine learning framework popular for research and production, developed by Meta.",
  opencv: "An open-source computer vision library for image and video processing tasks.",
  maven: "A build automation and dependency management tool for Java projects.",
  gradle: "A modern build automation tool for JVM languages with performant incremental builds.",
  junit: "A widely-used unit testing framework for Java that supports repeatable tests.",
  composer: "A dependency manager for PHP that handles packages and autoloading.",
  phpunit: "A unit testing framework for PHP for writing and running automated tests.",
  rspec: "A behavior-driven development (BDD) testing framework for Ruby applications.",
  css: "The style sheet language used to define the look and layout of web pages (alias for css3).",
  html: "The markup language used to structure web content (alias for html5).",
  appwrite: "An open-source backend server that provides APIs for database, auth, storage, and functions.",
};